name: drmid
version: 1.0.0+1
description: A new Flutter project.
publish_to: "none" # DO NOT REMOVE AS IT PUBLISHES THE PROJECT TO pub.dev
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_localized_locales: ^2.0.3
  flutter_spinkit: ^4.1.2+1
  dio: 1.0.0
  percent_indicator: ^3.4.0
  google_fonts: ^2.1.0
  url_launcher: ^6.0.2
  flutter_svg: ^0.22.0
  syncfusion_flutter_charts: ^19.3.44
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.1.0
  cupertino_icons: ^0.1.3
  flutter_tabler_icons: ^1.0.2
  provider: ^6.0.1
  cool_alert: ^1.0.3
  google_nav_bar: ^5.0.2
  carousel_slider: ^4.0.0
  geolocator: ^7.3.1
  geocoding: ^2.0.0
  html: ^0.15.0
  cached_network_image: ^3.1.0
  font_awesome_flutter: ^9.1.0
  typicons_flutter: ^0.4.2
  quick_actions: ^0.5.0
  nb_utils: ^4.4.8
  flutter_phoenix: ^1.0.0
  introduction_screen: ^2.0.0
  country_code_picker: ^2.0.2
  flutter_custom_clippers: ^2.0.0
  flutter_icons: ^1.1.0
  # Firebase
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  firebase_messaging: ^10.0.8
  firebase_storage: ^10.0.5
  # /Firebase
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_gen: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/fruits/
    - assets/icons/
    - assets/zip/
  generate: true
